config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users
  resource :posts, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, length: { minimum: 3 }
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 5 }

  has_many :posts

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to root_path, notice: "Post successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>All posts</h1>
<div>
  <% @posts.each do |post|%>
    <div>
      <p><%= post.title %></p>
      <p><%= post.body %></p>
      <p><%= post.user.username %></p>
    </div><br />
  <% end %>
  <% if user_signed_in? %>
    <%=link_to "new post", new_posts_path %>
    <%=button_to "Sign Out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%=link_to "Sign in to post", new_user_session_path %>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post do |form| %>
  <%= form.label "title" %>
  <%= form.text_field :title %><br><br>
  <%= form.label "body" %>
  <%= form.text_area :body %><br><br>
  <%= form.submit "post" %>
<% end %>